# Fashion MNIST Dataset

Context:

Fashion-MNIST is a dataset of Zalando's article images—consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes. Zalando intends Fashion-MNIST to serve as a direct drop-in replacement for the original MNIST dataset for benchmarking machine learning algorithms. It shares the same image size and structure of training and testing splits.

Labels

Each training and test example is assigned to one of the following labels:

1.T-shirt/top

2.Trouser

3.Pullover

4.Dress

5.Coat

6.Sandal

7.Shirt

8.Sneaker

9.Bag

10.Ankle boot

TL/DR

1.Each row is a separate image

2.Column 1 is the class label.

3.Remaining columns are pixel numbers (784 total).

4.Each value is the darkness of the pixel (1 to 255)

# Importing Libraries and Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
pixel=pd.read_csv("C:/Users/shapunya vemula/Downloads/fashion-mnist_train.csv.zip")

In [3]:
pixel.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
label = pixel.pop("label")

In [5]:
label.head()

0    2
1    9
2    6
3    0
4    3
Name: label, dtype: int64

In [15]:
sample = pixel.loc[9]

In [16]:
sample = np.array(sample, dtype= 'uint8')

In [17]:
sample = sample.reshape((28,28))

In [18]:
sample

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
          0, 141,  45,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0,
         86, 103,  65,  42,   0,   3,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
        162,   0,  88, 150,   0,   7,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,   0,  45,
        138,   0,  34, 156,   0,   1,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   4,   0, 118,
         51,   0,   0, 170,   0,   0,   1,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 153,
          0,   1,   0, 147,  71,   0,   4,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [19]:
pixel.loc[9].values

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,
         0, 141,  45,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         6,   0,  86, 103,  65,  42,   0,   3,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   1,   0, 162,   0,  88, 150,   0,   7,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   3,   0,  45, 138,   0,  34, 156,   0,   1,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   4,   0, 118,  51,   0,   0, 170,   0,
         0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0, 153,   0,   1,   0,
       147,  71,   0,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   3,   0,  50, 15

In [20]:
label.loc[9]

8

In [21]:
pixel.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       5       0   
3       0       0       0       1       2       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0        0  ...         0         0         0         0         0         0   
1        0  ...         0         0         0         0         0         0   
2        0  ...         0         0         0        30        43         0   
3        0  ...         3         0         0         0         0         1   
4        0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

# Making an image of a particular 28 x 28 matrix data¶

In [22]:
sample_pixel = pixel.loc[9]
sample_label = label.loc[9]
sample_pixel = np.array(sample_pixel, dtype="uint8")
sample_pixel = sample_pixel.reshape((28,28))
plt.title("Fashion MNIST category is {}".format(sample_label))
plt.imshow(sample_pixel, cmap="gray")
plt.show()

In [23]:
X_train = pixel
y_train = label
print(X_train.shape, y_train.shape)

(60000, 784) (60000,)


In [24]:
test = pd.read_csv("C:/Users/shapunya vemula/Downloads/fashion-mnist_test.csv (1).zip")
test.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [25]:
X_test = test.iloc[0:, 1:]
y_test = test.iloc[0:, 0]

In [26]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(60000, 784) (60000,) (10000, 784) (10000,)


# Defining a Model and Training each 28 x 28 Matrix Data to predict the Category.

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [28]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix


In [31]:
accuracy_score(y_test, y_pred)

0.8845

In [32]:
confusion_matrix(y_test, y_pred)

array([[865,   0,  13,  31,   0,   1,  79,   0,  11,   0],
       [  2, 971,   6,  15,   1,   1,   4,   0,   0,   0],
       [  6,   1, 810,  11, 111,   0,  52,   0,   9,   0],
       [ 18,   6,   7, 930,  20,   0,  19,   0,   0,   0],
       [  1,   0,  67,  29, 856,   0,  44,   0,   3,   0],
       [  0,   0,   0,   0,   0, 948,   0,  36,   5,  11],
       [173,   2,  99,  26,  78,   0, 607,   0,  15,   0],
       [  0,   0,   0,   0,   0,  14,   0, 934,   0,  52],
       [  2,   1,   9,   0,   3,   1,   6,   2, 976,   0],
       [  0,   0,   1,   0,   0,   8,   0,  40,   3, 948]], dtype=int64)